compute_environment: LOCAL_MACHINE
distributed_type: 'MULTI_GPU'  # Use MULTI_GPU for DPO
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16 # or fp16
num_machines: 1
num_processes: 2 # The number of GPUs you are using
rdzv_backend: static
same_network: true
tpu_env: []
use_cpu: false